name: tasks
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  go_router: ^16.2.0
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  equatable: ^2.0.7




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
#  To add font for ex
#  fonts:
#    - family: Cairo
#      fonts:
#        - asset: assets/fonts/Cairo-Regular.ttf
#        - asset: assets/fonts/Cairo-Bold.ttf
#          weight: 700
