name: tasks
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1

  # Networking
  dio: ^5.7.0

  # Local Storage
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI Helpers
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1

  # Date & Time
  intl: ^0.19.0

  # Cached images
  cached_network_image: ^3.4.1

  # Equatable (for States)
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
#  To add font for ex
#  fonts:
#    - family: Cairo
#      fonts:
#        - asset: assets/fonts/Cairo-Regular.ttf
#        - asset: assets/fonts/Cairo-Bold.ttf
#          weight: 700
